### ISSUE TITLE
Boceto y descripción del proyecto

### ISSUE THREAD

**Issue by alu0100825145** [alu0100826999/proyecto-stw#2]
Primer boceto del proyecto final
![boceto](https://user-images.githubusercontent.com/14940647/31769255-cb2212ec-b4ca-11e7-8a2c-c814acd46d5c.jpg)

**Comment by alu0100767001** [comment]
Aquí está la descripción del proyecto :+1: 
[ANTEPROYECTO SYTW.pdf](https://github.com/alu0100826999/proyecto-stw/files/1401559/ANTEPROYECTO.SYTW.pdf)
